docker/.git-completion.bash, docker/.qnxbashrc, docker/Dockerfile
Can we add git autocompletion to the docker container for QNXe ?
see: https://pagepro.co/blog/autocomplete-git-commands-and-branch-names-in-terminal/
=> add git autocompletion

.github/workflows/qt.yml, ports/qt/README.md, ports/qt/common.mk
=> qt (testing workflow)

.github/workflows/gflags.yml, ports/gflags/Makefile, ports/gflags/README.md, ports/gflags/common.mk, ports/gflags/nto-aarch64-le/Makefile, ports/gflags/nto-x86_64-o/Makefile, ports/gflags/qnx.nto.toolchain.cmake, ports/gflags/qnxtest.sh, ports/memory/README.md
Marking as draft for purposes of uploading test results
[out_x86_64.txt](https://github.com/user-attachments/files/18012865/out_x86_64.txt)
[out_x86_64.txt](https://github.com/user-attachments/files/18012866/out_x86_64.txt)
=> gflags from gitlab, github/qnx

.github/workflows/abseil-cpp.yml, .github/workflows/re2.yml, ports/abseil-cpp/README.md, ports/abseil-cpp/common.mk, ports/re2/Makefile, ports/re2/README.md, ports/re2/common.mk, ports/re2/nto-aarch64-le/Makefile, ports/re2/nto-x86_64-o/Makefile, ports/re2/qnx.nto.toolchain.cmake, ports/re2/run_tests.sh
=> re2 moved from GitLab

.github/workflows/libxml2.yml, ports/libxml2/README.md
=> libxml2: new

.github/workflows/azure-iot-sdk-c.yml, ports/azure-iot-sdk-c/README.md, ports/azure-iot-sdk-c/scripts/patch.sh
README and GitHub Action changes to rightly apply submodule patches.
=> azure-iot-sdk-c: Update README.md and GitHub Actions

.github/workflows/qt.yml, .github/workflows/sqlite_orm.yml
workflow changes to cache sdp 8 download
=> workflows for: qt and sqlite_orm

ports/pandas/.gitignore, ports/pandas/Makefile, ports/pandas/README.md, ports/pandas/common.mk, ports/pandas/nto-aarch64-le/Makefile, ports/pandas/nto-x86_64-o/Makefile
Adds build files and build instructions for pandas on SDP 7.1 and SDP 8.0
=> pandas: add build files

.github/workflows/tftp-hpa.yml, ports/tftp-hpa/README.md, ports/tftp-hpa/fix-build-gcc-10.patch, ports/tftp-hpa/qnx-sa-restart.patch
Just need some ifndef magic to make it work.
=> tftp-hpa: new

resources/meson/x86_64/qnx700.ini, resources/meson/x86_64/qnx710.ini, resources/meson/x86_64/qnx800.ini, resources/meson/x86_64/workflows/qnx800.ini
added meson cross file for x86_64 architecture for sdp 7.0, 7.1, 8.0
=> Meson cross-file for x86_64 architecture

ports/OpenBLAS/Makefile, ports/OpenBLAS/README.md, ports/OpenBLAS/common.mk, ports/OpenBLAS/nto-aarch64-le/Makefile, ports/OpenBLAS/nto-x86_64-o/Makefile, ports/OpenBLAS/qnx.nto.toolchain.cmake, ports/OpenBLAS/qnxtests.sh
Adds build files and build instructions for OpenBLAS. All tests pass.
=> OpenBLAS: add build files

.github/workflows/Fast-DDS.yml, ports/Fast-DDS/Makefile, ports/Fast-DDS/README.md, ports/Fast-DDS/common.mk, ports/Fast-DDS/nto/Makefile, ports/Fast-DDS/nto/aarch64/Makefile, ports/Fast-DDS/nto/aarch64/le/Makefile, ports/Fast-DDS/nto/x86_64/Makefile, ports/Fast-DDS/nto/x86_64/o/Makefile, ports/Fast-DDS/project_hooks.cmake, ports/Fast-DDS/qnx.nto.toolchain.cmake, ports/Fast-DDS/qnx_patches/Fast-DDS.patch, ports/Fast-DDS/qnx_patches/asio_qnx.patch, ports/Fast-DDS/qnx_patches/fastcdr_qnx.patch, ports/Fast-DDS/qnx_patches/googletest_qnx.patch, ports/Fast-DDS/qnx_patches/tinyxml2_qnx.patch
Move build files from Fast-DDS repo to build-files to mean new porting process.
=> Fast-DDS: Update to new workflow

.github/workflows/dlt-daemon.yml
=> dlt-daemon: add a workflow

.github/workflows/asio.yml, ports/asio/Makefile, ports/asio/README.md, ports/asio/build-hooks, ports/asio/nto-aarch64-le/GNUmakefile, ports/asio/nto-x86_64-o/GNUmakefile
build files and workflow for asio library
=> add build files and tests instruction for asio lib

.github/workflows/lely-core.yml, ports/lely-core/Makefile, ports/lely-core/README.md, ports/lely-core/build-hooks, ports/lely-core/nto-aarch64-le/GNUmakefile, ports/lely-core/nto-x86_64-o/GNUmakefile
Setup build and test infrastructure for ECSS compliant lely-core.
Workflows were also updated
=> add build files and test instructions for ECSS compliant port lely-core

.github/workflows/cairo.yml, ports/cairo/.gitignore, ports/cairo/Makefile, ports/cairo/README.md, ports/cairo/cairo-test.patch, ports/cairo/common.mk, ports/cairo/install_all.sh, ports/cairo/nto-aarch64-le/Makefile, ports/cairo/nto-x86_64-o/Makefile, ports/cairo/qnx_cross.cfg.in
Update to existing QSC pacakges and qnx-ports package
...
Waiting on #95 #96
=> cairo update: add recusive make file and detail tests intructions

ports/perl5/Makefile, ports/perl5/README.md, ports/perl5/build-hooks, ports/perl5/nto-aarch64-le/GNUmakefile, ports/perl5/nto-x86_64-o/GNUmakefile
built with 7.1/8.0
tested on qemu 8.0.2
=> add build files and test instructions for per5/perl-cross

.github/workflows/perl5.yml, ports/perl5/Makefile, ports/perl5/README.md, ports/perl5/build-hooks, ports/perl5/nto-aarch64-le/GNUmakefile, ports/perl5/nto-x86_64-o/GNUmakefile
perl5/perl-cross: update ci to add perl workflow
=> Perl5/perl-cross CI update

.github/workflows/Fast-DDS.yml
=> Add 7.1 workflow for Fast-DDS.

docker/Dockerfile, docker/abuild_qnx.patch
Added:
- apk-tools (v3.0.0_rc4)
- abuild (patched for QNX)
=> add support for apk build toolchain

.github/workflows/restbed.yml, ports/restbed/Makefile, ports/restbed/README.md, ports/restbed/base_testsuite.py, ports/restbed/common.mk, ports/restbed/ctest.py, ports/restbed/decode_ctest.py, ports/restbed/nto-aarch64-le/Makefile, ports/restbed/nto-x86_64-o/Makefile, ports/restbed/qnx.nto.toolchain.cmake
add build and test setup for Restbed
workflow updated
=> add build files and test instructions for restbed

ports/abseil-cpp/common.mk, ports/protobuf/common.mk, ports/re2/common.mk
This MR is mostly to test the workflow before merging.
=> Fix install paths for packageConfig.cmake projects

.github/workflows/glib.yml, ports/glib/README.md, ports/glib/common.mk, ports/glib/qnx_cross.cfg.in
...
Glib is now updated to 2.84.1
=> update glib to 2.84.1 to fix CVEs

docker/README.md, docker/docker-create-container.sh, docker/welcome.sh
mount only following directories:
.qnx
qnx800
qnx_workspace
JIRA: QNXOSG-757
=> docker: make docker container safer

.github/workflows/sdp-build-env.yml
=> sdp-build-env: Update sdp-build-env.yml

.github/workflows/conan-protobuf.yml, README.md
setup protobuf conan build workflow
=> conan: protobuf workflow

.github/workflows/conan-up-core-api.yml, .github/workflows/conan-up-cpp.yml, README.md
setup up-core-api and up-cpp conan build workflows
=> conan: uProtocol workflow

.github/workflows/conan-zenoh-cpp.yml, .github/workflows/conan-zenoh-pico.yml, README.md
setup zenoh-pico and zenoh-cpp conan build workflows
=> conan: Zenoh workflow

.github/workflows/glib.yml, ports/glib/README.md, ports/glib/qnx_cross.cfg.in
=> glib: update to 2.84.3

.github/workflows/cairo.yml, .github/workflows/fontconfig.yml, .github/workflows/freetype.yml, .github/workflows/gdk-pixbuf.yml, .github/workflows/gettext-runtime.yml, .github/workflows/glib.yml, .github/workflows/harfbuzz.yml, .github/workflows/libiconv.yml, .github/workflows/libpng.yml, .github/workflows/libthai.yml, .github/workflows/pixman.yml, ports/cairo/install_all.sh, ports/fontconfig/install_all.sh, ports/freetype/install_all.sh, ports/gdk-pixbuf/install_all.sh, ports/glib/install_all.sh, ports/harfbuzz/install_all.sh, ports/libpng/install_all.sh, ports/libthai/install_all.sh
...
This will ensure a chained failure on install_all.sh once an error is detected.
=> Update ci and install_all.sh for: cairo, fontconfig, freetype, gdk-pixbuf, glib, pixman, gettext-runtime, libiconv, harfbuzz, libthai, libpng
